spring.application.name=atencionclinica
server.port=8081

# URL: localhost, puerto 3306 (por defecto en XAMPP) y el nombre de tu DB
spring.datasource.url=jdbc:mysql://localhost:3306/Castro_atencionclinica?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Formatea el SQL en la consola para que sea legible
spring.jpa.properties.hibernate.format_sql=true